name: release-client CI/CD
on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  build-image:
    name: CI/CD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Node 설정
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: node_modules 폴더 캐싱
        uses: actions/cache@v2
        id: cache
        with:
          path: "**/frontend/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/client/yarn.lock') }}

      - name: node_modules 폴더 캐시가 없다면 dependencies 설치
        working-directory: "./frontend"
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Client 소스 빌드
        working-directory: "./client"
        run: npm build
